In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5,6,7,8]

In [3]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
nested_list = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(start=0, stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [13]:
np.linspace(0, 10, 31)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667,  2.        ,  2.33333333,  2.66666667,  3.        ,
        3.33333333,  3.66666667,  4.        ,  4.33333333,  4.66666667,
        5.        ,  5.33333333,  5.66666667,  6.        ,  6.33333333,
        6.66666667,  7.        ,  7.33333333,  7.66666667,  8.        ,
        8.33333333,  8.66666667,  9.        ,  9.33333333,  9.66666667,
       10.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.49900873, 0.90296429, 0.69059023, 0.99475596, 0.86310754])

In [16]:
np.random.rand(3,4)

array([[0.59214799, 0.66475114, 0.89933551, 0.19467371],
       [0.25325929, 0.30774903, 0.78136137, 0.18249926],
       [0.93256798, 0.09581382, 0.51443595, 0.06322916]])

In [17]:
np.random.randint(1, 100)

78

In [18]:
np.random.randn(5,5)

array([[ 1.29167357, -1.83717066,  1.80301525,  1.20629705,  1.13216312],
       [-1.5804835 ,  1.06602752, -0.20735574,  0.72688258,  0.17344377],
       [ 0.10991448, -0.65422273,  1.63007313, -1.56738812,  0.27491318],
       [ 1.52385836, -0.03456277,  0.00921497, -1.00900824, -0.06943138],
       [ 0.28675794,  0.99816566,  0.34125018,  0.96207927,  0.34988726]])

In [19]:
arr = np.arange(25)

In [20]:
ranarr = np.random.randint(0, 50, 10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([25, 19, 44, 34, 42, 22, 14, 44,  0, 34])

In [23]:
arr.shape

(25,)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max(), ranarr.min()

(44, 0)

In [26]:
ranarr.argmax(), ranarr.argmin()

(2, 8)

In [27]:
ranarr.dtype

dtype('int64')