In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
arr[-1:]

array([10])

In [9]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[-5:-1]

array([6, 7, 8, 9])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
slice = arr[:5]

In [15]:
slice, arr

(array([0, 1, 2, 3, 4]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [16]:
slice = 99

In [17]:
slice

99

In [18]:
slice = arr[:5]

In [19]:
slice[:] = 100

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[1]

array([20, 25, 30])

In [25]:
arr_2d[1,1], arr_2d[1][1]

(25, 25)

In [26]:
arr = np.arange(1, 11)

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr > 4

In [29]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])